#!/bin/bash

echo "."
echo "Ximena bash scrip [Versión 1.0]"
echo "(c) Corporation. Todos los derechos reservados."
echo "[ ██ Desintalador de programas para Linux Mint xfce, v1.0.4, se iniciara la Desinstalacion."
echo "."

echo " "
echo "+--------------------------------------------------+"
echo "|      Ximena bash scrip [Versión 1.2]             |"
echo "|  (c) Corporation. Todos los derechos reservados. |"
echo "|                                                  |"
echo "|    *** SCRIPT PARA EL APAGADO DEL EQUIPO ***     |"
echo "+--------------------------------------------------+"
echo " "

echo " "
echo -e "\e[0;38;5;141m+------------\e[0m"
echo -e "\e[0;38;5;141m|            \ \e[0m"
echo -e "\e[0;38;5;141m|             ------------------------------------+\e[0m"
echo -e "\e[0;38;5;141m|                                                 |\e[0m"
echo -e "\e[0;38;5;141m|       Ximena bash scrip [Versión 1.3]          |\e[0m"
echo -e "\e[0;38;5;141m|                                                 |\e[0m"
echo -e "\e[0;38;5;141m| (c) Corporation. Todos los derechos reservados, |\e[0m"
echo -e "\e[0;38;5;141m|                                                 |\e[0m"                                       
echo -e "\e[0;38;5;141m|                                                 |\e[0m"
echo -e "\e[0;38;5;141m|  *Se creara y montara en la carpeta redMount    |\e[0m"
echo -e "\e[0;38;5;141m|        de la ubucacion de usuario ~/            |\e[0m"
echo -e "\e[0;38;5;141m|                                                 |\e[0m"
echo -e "\e[0;38;5;141m+-------------------------------------------------+\e[0m"  

echo "."
echo "   ____ ____ ____ ____ ____ ____ _________ ____ ____ ____ ____ _________ ____ ____ ____ ____ ____" 
echo "  ||X |||i |||m |||e |||n |||a |||       |||b |||a |||s |||h |||       |||s |||c |||r |||i |||p ||"
echo "  ||__|||__|||__|||__|||__|||__|||_______|||__|||__|||__|||__|||_______|||__|||__|||__|||__|||__||"
echo "  |/__\|/__\|/__\|/__\|/__\|/__\|/_______\|/__\|/__\|/__\|/__\|/_______\|/__\|/__\|/__\|/__\|/__\|"
echo "Ximena bash scrip [Versión 1.4]"


echo "  _    _ _                            _                _                         _"       
echo " \ \  / (_)                          | |              | |                       (_) "     
echo "  \ \/ / _ ____   ____ ____   ____   | | _   ____  ___| | _      ___  ____  ____ _ ____"  
echo "   )  ( | |    \ / _  )  _ \ / _  |  | || \ / _  |/___) || \    /___)/ ___)/ ___) |  _ \ " 
echo "  / /\ \| | | | ( (/ /| | | ( ( | |  | |_) | ( | |___ | | | |  |___ ( (___| |   | | | | | "
echo " /_/  \_\_|_|_|_|\____)_| |_|\_||_|  |____/ \_||_(___/|_| |_|  (___/ \____)_|   |_| ||_/  "
echo "                                                                                  |_|    "
echo "Ximena bash scrip [Versión 1.5]"

echo "."
echo "                    l.                     _    _ _  "
echo "                    llb                   \ \  / (_) "
echo "             ..:''  lllb l:                \ \/ / _ ____   ____ ____   ____  "
echo "  '::.     .:'      llllb  ':.              )  ( | |    \ / _  )  _ \ / _  | "
echo "      ''l::         llllb   'l.            / /\ \| | | | ( (/ /| | | ( ( | | "
echo "         ;'lllb:.    llllP     l          /_/  \_\_|_|_|_|\____)_| |_|\_||_| "
echo "        :    'lllllb lllli      l     "
echo "        l       'QllllllllL.    l          _                _                         _"
echo "        l          :llllllPl.   l         | |              | |                       (_) "
echo "         l       .:llllP'      l'         | | _   ____  ___| | _      ___  ____  ____ _ ____"
echo "          l    .;llP'        .l'          | || \ / _  |/___) || \    /___)/ ___)/ ___) |  _ \ "
echo "           'l.' .'         .lP'           | |_) | ( | |___ | | | |  |___ ( (___| |   | | | | | "
echo "         .-' ':+..     ..+l'              |____/ \_||_(___/|_| |_|  (___/ \____)_|   |_| ||_/  "
echo "       '     '    '''''                                                                |_|    "
echo "."
echo "Ximena bash scrip [Versión 1.6]"

echo "                 llll  "
echo "                 llll  "
echo -e " pppp .ppppp.    llll    .eeeeeee. \e[0;38;5;178m'xxxx.\e[0m   .xxxx'  "
echo -e " ppppppppppppp.  llll   eeeee''eeee. \e[0;38;5;178m'xxxx.\e[0m'xxxx'  "
echo -e " pppp'     'ppp. llll  eeee'    'eee. \e[0;38;5;178m'xxxx.\e[0m'xx'  "
echo -e " pppp       pppi llll  eeeeeeeeeeeeee  \e[0;38;5;178m'xxxx>\e[0m'  "
echo -e " pppp.     .ppp' llll  eeee           \e[0;38;5;178m.xxxx'\e[0m.xx. "
echo -e " pppppp,,,pppp'  lllll  eeee...eeee; \e[0;38;5;178m.xxxx'\e[0m.xxxx. "
echo -e " pppp pppppp'     llll'  'eeeeeee;  \e[0;38;5;178m.xxxx'\e[0m  'xxxx.  "
echo -e " pppp   '''        ''       ''''    \e[0;38;5;178m'''''\e[0m     '''''  "
echo -e " pppp  "
echo -e " '''  "
echo "Ximena bash scrip (plex) [Versión 1.7]"

echo " "
echo -e "\e[0;38;5;129m                      I.        \e[0m"
echo -e "\e[0;38;5;129m                      XIm       \e[0m"
echo -e "\e[0;38;5;129m                  ....XIIm .               _    _ _    \e[0m"
echo -e "\e[0;38;5;135m             ..;I''   IXIMI 'I;;          \ \  / (_)   \e[0m"
echo -e "\e[0;38;5;135m..        ..I'         XMMML    I;.        \ \/ / _ ____   ____ ____   ____   \e[0m"
echo -e "\e[0;38;5;135m  '';..  ;P            XIMENA     'I.       )  ( | |    \ / _  )  _ \ / _  |  \e[0m"
echo -e "\e[0;38;5;141m     ''XXi+.           :IMENA:      ':     / /\ \| | | | ( (/ /| | | ( ( | |  \e[0m"
echo -e "\e[0;38;5;141m      .:''IMENAi:.     :XIMEN:       ':   /_/  \_\_|_|_|_|\____)_| |_|\_||_|  \e[0m"
echo -e "\e[0;38;5;141m      X    '':XIMENA:  :IMENA         I;   \e[0m"
echo -e "\e[0;38;5;147m      I        '';BACHSCRIPXIL.        I   _                _                         _  \e[0m"
echo -e "\e[0;38;5;147m      M           '';XIMENABASHXL      I  | |              | |                       (_) \e[0m"
echo -e "\e[0;38;5;147m      E              ;XXXBASHP*''*     I  | | _   ____  ___| | _      ___  ____  ____ _ ____ \e[0m"
echo -e "\e[0;38;5;153m       N          .4XIMENAP'          I   | || \ / _  |/___) || \    /___)/ ___)/ ___) |  _ \  \e[0m"
echo -e "\e[0;38;5;153m        A       .;XIMP''            .I    | |_) | ( | |___ | | | |  |___ ( (___| |   | | | | | \e[0m"
echo -e "\e[0;38;5;153m         'B. .;'' ;'              .;I     |____/ \_||_(___/|_| |_|  (___/ \____)_|   |_| ||_/  \e[0m"
echo -e "\e[0;38;5;159m          .;A    I            ..;I'                                                    |_|     \e[0m"
echo -e "\e[0;38;5;159m       .*'   '';I..       ..;;I'    \e[0m"
echo -e "\e[0;38;5;159m     ''       '    ''''''''         \e[0m"
echo " "
echo "Ximena bash scrip [Versión 1.7]"
echo "(c) Corporation. Todos los derechos reservados, "
echo " "

#chmod 777 installApps.sh
#Ejecutar con ./installApps.sh

# lun 05 sep 2022 14:45:34
# jue 08 dic 2022 13:24:22 CST